M48
; DRILL file {KiCad 9.0.0} date 2025-03-18T00:42:33+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-18T00:42:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X6.589Y-3.0553
X6.8165Y-3.0553
T2
X6.2598Y-2.9329
X6.378Y-2.9329
M30
